/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux sd8server88 2.6.38-13-generic-pae #56-Ubuntu SMP Tue Feb 14 14:32:30 UTC 2012 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Thu Oct  4 18:44:10 CST 2012"
#define BUILD_ENV_SRCDIR "/home/keith_huang/11n/rlx/patch_area/rtl819x-SDK-v32_v321_v3211_322_3221/rtl819x/users/samba/samba-3.2.15/source"
#define BUILD_ENV_BUILDDIR "/home/keith_huang/11n/rlx/patch_area/rtl819x-SDK-v32_v321_v3211_322_3221/rtl819x/users/samba/samba-3.2.15/source"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "sd8server88"
#define BUILD_ENV_COMPILER "mips-linux-gcc"
#endif /* _BUILD_ENV_H */
